### ISSUE TITLE
SDK 2.0.0 docs review

### ISSUE THREAD

**Issue by ravi-cm** [delphix/virtualization-sdk#100]
** Expected Behavior**
Describe what should have happened.

** Actual Behavior**
Describe what actually happened.

**Steps To Reproduce the Problem**
Describe in as much detail as possible how to reproduce the problem.

**Screenshots**

**Version**
Indicate the relevant versions of components. This may include the package version, operating system version, or other components relevant to the project.

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by nhlien93** [comment]
Some comments on what might make sense to change in this doc change too:
- **Building your first Plugin > Overview > Prerequisites** ->
 `A running Delphix Engine, version x.y.z or above should actually be 6.0.2 (? Since this is SDK 2.0.0?)

- **Building your first Plugin > Initial Setup > Sanity check** ->
For the pasted text output of dvp -h we should verify the output is still the same. Otherwise update it

- **Building your first Plugin > Initial Setup > Creating a Bare Plugin** ->
Verify that the dvp init -h output is correct.

- **Building your first Plugin > Initial Setup > Uploading the New Plugin** ->
The screenshot still has the Toolkit title. We should take a new one with Plugin (also new upgrade icon exists now)

- **References > CLI > Help > Examples** ->
The dvp -h output looks out of date. We should update it.

- **References > CLI > upload** >
Need to add the —wait option

- **References > CLI > upload > Examples** ->
Upload artifact build/artifact.json to delphix-engine.domain using the user admin. Since the password option is ommitted, a secure password prompt is used instead.

```
$ dvp upload -a build/artifact -e engine.example.com -u admin
Password:
The engine’s hostname was not the same, we should fix this.
```


- **References > CLI** ->
Nit: some of the examples don’t show if anything gets returned/written after. Would be nice to include in examples the results.

- **References > Plugin Config > Examples** ->
This is a valid plugin config for the plugin:
```
id: 7cf830f2-82f3-4d5d-a63c-7bbe50c22b32
name: MongoDB
version: 2.0.0
hostTypes:
  - UNIX
entryPoint: mongo_runner:mongodb
srcDir: src/
schemaFile: schema.json
pluginType: DIRECT
language: PYTHON27
```
Fix the example to have buildNumber/eternalVersion for both examples
Maybe we should move versioning and upgrading above references? (Mostly because references has a glossary which feels like it should be close to the “end”

- **Versioning And Upgrading > Versioning > versioning Information > External Version** ->
Maybe add a NOTE saying that we recommend the external version be easy to understand in terms of what version is higher than another version. This makes it easier for the user to know by looking just at the external version 

- **Versioning And Upgrading > Versioning > versioning Information > Build Number** ->
The for example part could potentially be in a NOTE box?

- **Versioning And Upgrading > Compatibility > Delphix Engine Rules** ->
The build number may only move forward == do we want to explicitly say equal build number is okay? (Also maybe here is a good part to say any changes should update the build number but while writing the plugin it’s not necessary?
